#!/bin/sh
#deploy="false"
deploy="true"

image=EXAM_FINAL_CLIENT
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t vivekmaniyar/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push vivekmaniyar/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag vivekmaniyar/${image}:1.0-SNAPSHOT vivekmaniyar/${image}:latest
        docker push vivekmaniyar/${image}:latest
    fi
fi