#!/bin/sh
mvn clean package && docker build -t vivekmaniyar/EXAM_FINAL_CLIENT .
docker rm -f EXAM_FINAL_CLIENT 2>/dev/null || true && docker run -it --name EXAM_FINAL_CLIENT -p 8080:8080 -p 4848:4848 -p 8181:8181 --name EXAM_FINAL_CLIENT vivekmaniyar/EXAM_FINAL_CLIENT
